.build_template: &build_definition
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - IMAGE_NAME=${CI_JOB_NAME%_*}
    - export IMAGE_NAME=${IMAGE_NAME/-/\/}
    - export IMAGE_TAG=${CI_JOB_NAME#*_}
    - export IMAGE=$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG || true
    - >
      docker build
      --pull
      --cache-from $IMAGE
      --rm=false
      --tag $IMAGE .
      --file $CI_JOB_NAME
    - docker push $IMAGE

.deploy_template: &release_definition
  stage: deploy
  after_script:
    - export DHUB_IMAGE_NAME=$DOCKER_HUB_USER/$IMAGE_NAME
    - docker logout
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN docker.io
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG

builder-alpine_latest: # builder/alpine:latest
  <<: *build_definition

ntpsec_alpine: # ntpsec:alpine
  <<: *build_definition
  <<: *release_definition
  after_script:
    - docker tag $IMAGE $DHUB_IMAGE_NAME:latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine3
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine3
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-alpine_edge: # builder/alpine:edge
  <<: *build_definition

ntpsec_alpine-edge: # ntpsec:alpine-edge
  <<: *build_definition
  <<: *release_definition
  after_script:
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine-edge
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-centos_latest: # builder/centos:latest
  <<: *build_definition

ntpsec_centos: # ntpsec:centos
  <<: *build_definition
  <<: *release_definition
  after_script:
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8.2
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8.2
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-debian_latest: # builder/debian:latest
  <<: *build_definition

ntpsec_debian: # ntpsec:debian
  <<: *build_definition
  <<: *release_definition
  after_script:
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10.4
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10.4
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME