image: docker:stable
services:
  - docker:stable-dind

.build_template: &build_template
  stage: build
  before_script:
    - IMAGE_NAME=${CI_JOB_NAME%_*}
    - export IMAGE_NAME=${IMAGE_NAME/-/\/}
    - export IMAGE_TAG=${CI_JOB_NAME#*_}
    - export IMAGE=$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  script: &build_script
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE || true
    - >
      docker build
      --pull
      --cache-from $IMAGE
      --rm=false
      --tag $IMAGE .
      --file $CI_JOB_NAME
    - docker push $IMAGE

.deploy_template:
  <<: *build_template
  stage: deploy
  script: &deploy_script
    - export DHUB_IMAGE_NAME=$DOCKER_HUB_USER/$IMAGE_NAME
    - docker logout
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN docker.io
    - docker tag $IMAGE $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG

builder-alpine_3.12: # builder/alpine:3.12
  extends: .build_template
  only:
    changes:
      - ntpsec_alpine3.12
      - builder-alpine_3.12
      - ntp.conf

ntpsec_alpine3.12: # ntpsec:alpine
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:latest # Core Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine # Alpine Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine-latest # Alpine Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine3
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine3.12
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine3.12.0
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine # Alpine Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine3
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine3.12
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine3.12.0
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-alpine_3.12"]
  only:
    changes:
      - ntpsec_alpine3.12
      - builder-alpine_3.12
      - ntp.conf

builder-alpine_edge: # builder/alpine:edge
  extends: .build_template
  only:
    changes:
      - ntpsec_alpine-edge
      - builder-alpine_edge
      - ntp.conf

ntpsec_alpine-edge: # ntpsec:alpine-edge
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine-edge
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine-edge
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-alpine_edge"]
  only:
    changes:
      - ntpsec_alpine-edge
      - builder-alpine_edge
      - ntp.conf

builder-centos_8: # builder/centos:8
  extends: .build_template
  only:
    changes:
      - ntpsec_centos8
      - builder-centos_8
      - ntp.conf

ntpsec_centos8: # ntpsec:8
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos # CentOS Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos-latest # CentOS Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8.2
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos # CentOS Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8.2
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-centos_8"]
  only:
    changes:
      - ntpsec_centos8
      - builder-centos_8
      - ntp.conf

builder-debian_10: # builder/debian:10
  extends: .build_template
  only:
    changes:
      - ntpsec_debian10
      - builder-debian10
      - ntp.conf

ntpsec_debian10: # ntpsec:10
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-buster
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10.4
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10.4
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-debian_10"]
  only:
    changes:
      - ntpsec_debian10
      - builder-debian10
      - ntp.conf

builder-debian_10-slim: # builder/debian:10-slim
  extends: .build_template
  only:
    changes:
      - ntpsec_debian10-slim
      - builder-debian_10-slim
      - ntp.conf

ntpsec_debian10-slim: # ntpsec:debian10-slim
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian # Debian Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-latest # Debian Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-slim
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10-slim
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10.4-slim
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian # Debian Latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian-slim
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10-slim
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10.4-slim
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-debian_10-slim"]
  only:
    changes:
      - ntpsec_debian10-slim
      - builder-debian_10-slim
      - ntp.conf

builder-debian_testing: # builder/debian:testing
  extends: .build_template
  only:
    changes:
      - ntpsec_debian_testing
      - builder-debian_testing
      - ntp.conf

ntpsec_debian-testing: # ntpsec:debian-testing
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-testing
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian-testing
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
  needs: ["builder-debian_testing"]
  only:
    changes:
      - ntpsec_debian_testing
      - builder-debian_testing
      - ntp.conf