image: docker:stable
services:
  - docker:stable-dind

.build_template: &build_template
  stage: build
  before_script:
    - IMAGE_NAME=${CI_JOB_NAME%_*}
    - export IMAGE_NAME=${IMAGE_NAME/-/\/}
    - export IMAGE_TAG=${CI_JOB_NAME#*_}
    - export IMAGE=$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  script: &build_script
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE || true
    - >
      docker build
      --pull
      --cache-from $IMAGE
      --rm=false
      --tag $IMAGE .
      --file $CI_JOB_NAME
    - docker push $IMAGE
  only:
    changes:
      - ${CI_JOB_NAME}

.deploy_template:
  <<: *build_template
  stage: deploy
  script: &deploy_script
    - export DHUB_IMAGE_NAME=$DOCKER_HUB_USER/$IMAGE_NAME
    - docker logout
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN docker.io
    - docker tag $IMAGE $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG

builder-alpine_latest: # builder/alpine:latest
  extends: .build_template

ntpsec_alpine: # ntpsec:alpine
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:alpine3
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine3
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-alpine_edge: # builder/alpine:edge
  extends: .build_template

ntpsec_alpine-edge: # ntpsec:alpine-edge
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-alpine-edge
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-centos_latest: # builder/centos:latest
  extends: .build_template

ntpsec_centos: # ntpsec:centos
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:centos8.2
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-centos8.2
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

builder-debian_latest: # builder/debian:latest
  extends: .build_template

ntpsec_debian: # ntpsec:debian
  extends: .deploy_template
  script:
    - *build_script
    - *deploy_script
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian-latest
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:debian10.4
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10
    - docker tag $IMAGE $DHUB_IMAGE_NAME:1.1.9-debian10.4
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME