.build_template: &build_definition
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_FILE: "${CI_JOB_NAME/release-/}"
    IMAGE_NAME: "${DOCKER_FILE%_*}"
    IMAGE_NAME: "${IMAGE_NAME/-//}"
    IMAGE_TAG: "${CI_JOB_NAME#*_}"
    IMAGE_LABEL: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_LABEL || true
    - >
      docker build
      --pull
      --cache-from $IMAGE_LABEL
      --rm=false
      --tag $IMAGE_LABEL .
      --file $DOCKER_FILE
    - docker push $IMAGE_LABEL

.deploy_template: &release_definition
  stage: deploy
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_FILE: "${CI_JOB_NAME/release-/}"
    IMAGE_NAME: "${DOCKER_FILE%_*}"
    IMAGE_NAME: "${IMAGE_NAME/-//}"
    IMAGE_TAG: "${CI_JOB_NAME#*_}"
    IMAGE_LABEL: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_NS || true
    - >
      docker build
      --pull
      --cache-from $IMAGE_LABEL
      --rm=false
      --tag $IMAGE_LABEL .
      --file $DOCKER_FILE
    - docker push $IMAGE_LABEL
  after_script:
    - docker logout
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN docker.io
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG

build-builder-alpine_latest: # builder/alpine:latest
  <<: *build_definition

release-ntpsec_alpine: # ntpsec:alpine
  <<: *release_definition
  after_script:
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:latest
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:alpine-latest
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:alpine3
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-alpine
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-alpine3
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

build-builder-alpine_edge: # builder/alpine:edge
  <<: *build_definition

release-ntpsec_alpine-edge: # ntpsec:alpine-edge
  <<: *release_definition
  after_script:
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-alpine-edge
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

build-builder-centos_latest: # builder/centos:latest
  <<: *build_definition

release-ntpsec_centos: # ntpsec:centos
  <<: *release_definition
  after_script:
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:centos-latest
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:centos8
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:centos8.2
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-centos
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-centos8
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-centos8.2
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME

build-builder-debian_latest: # builder/debian:latest
  <<: *build_definition

release-ntpsec_debian: # ntpsec:debian
  <<: *release_definition
  after_script:
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:debian-latest
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:debian10
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:debian10.4
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-debian
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-debian10
    - docker tag $IMAGE_LABEL $DOCKER_HUB_USER/$IMAGE_NAME:1.1.9-debian10.4
    - docker push docker.io/$DOCKER_HUB_USER/$IMAGE_NAME
