FROM alpine:latest
LABEL maintainer "rouing"
LABEL description "NTP reference implementation, refactored for security"

ENV NTPSEC_BUILD_DEPS m4 tar gcc sed

RUN apk add --no-cache $NTPSEC_BUILD_DEPS

# https://github.com/ntpsec/ntpsec/releases
ENV NTPSEC_VERSION 1.1.9
ENV NTPSEC_DOWNLOAD_URL "https://ftp.ntpsec.org/pub/releases/ntpsec-${NTPSEC_VERSION}.tar.gz"
ENV NTPSEC_SHA256 0acade979a807a047c2a8fd7f497235d9d6a5d0d54726e5d27505506d6ec00cc

RUN set -x && \
    mkdir -p /tmp && \
    cd /tmp && \
    wget -O ntpsec.tar.gz $NTPSEC_DOWNLOAD_URL && \
    echo "${NTPSEC_SHA256} *ntpsec.tar.gz" | sha256sum -c - && \
    tar xzf ntpsec.tar.gz

RUN set -x && \
    cd /tmp/ntpsec-${NTPSEC_VERSION} && \
    sed -i 's/python --version/python3 --version/g' buildprep && \
    find /tmp/ntpsec-${NTPSEC_VERSION} \( -type d -name .git -prune \) -o -type f | xargs sed -i 's/env python/env python3/g' && \
    sed -i 's/$install build-base python                  # basic tools/$install build-base python3 linux-lts-dev busybox # basic tools/g' buildprep && \
    sed -i 's/# probably needs more, but this builds/$install py3-gpsd gpsd-dev/g' buildprep && \
    sed -i 's/# can'\''t find timepps.h: gpsd and chrony have their own ??/$install libc-dev openssl-dev/g' buildprep && \
    ./buildprep && \
    ./waf configure --prefix=/usr --python=python3 --enable-leap-smear --enable-mssntp --refclock=all && \
    ./waf build --verbose && \
    ./waf check --verbose && \
    ./waf install

#------------------------------------------------------------------------------#
FROM alpine:latest

ENV NTPSEC_RUN_DEPS python3 libressl libcap libseccomp py3-gpsd

RUN apk add --no-cache $NTPSEC_RUN_DEPS

COPY --from=0 /usr/sbin/ntpd /usr/sbin/ntpd
COPY --from=0 /usr/bin/ntp* /usr/bin/
COPY --from=0 /usr/lib/python3.8/site-packages/ntp/ /usr/lib/python3.8/site-packages/ntp/

RUN set -x && \
    mkdir -p /var/ntpsec/

COPY ntp.conf /etc/ntp.conf

EXPOSE 123/udp
EXPOSE 123/tcp

RUN ntpd --version

ENTRYPOINT ["/usr/sbin/ntpd"]

CMD ["-n", "-c", "/etc/ntp.conf"]
