FROM alpine:latest
LABEL maintainer "rouing"
LABEL description "NTP reference implementation, refactored for security"

ENV NTPSEC_BUILD_DEPS m4 tar gcc libc-dev bison libressl-dev libcap-dev libseccomp-dev python3-dev asciidoc openssl-dev linux-headers py3-gpsd python3 git busybox abuild patch

RUN apk add --no-cache $NTPSEC_BUILD_DEPS

# https://github.com/ntpsec/ntpsec/releases
ENV NTPSEC_VERSION 1.1.8
ENV NTPSEC_DOWNLOAD_URL "https://ftp.ntpsec.org/pub/releases/ntpsec-${NTPSEC_VERSION}.tar.gz"
ENV NTPSEC_SHA256 8445827a4d5029da508a11e9c8e7958db839f73b39de612ab3909244f89a1340

RUN set -x && \
    mkdir -p /tmp && \
    cd /tmp && \
    wget -O ntpsec.tar.gz $NTPSEC_DOWNLOAD_URL && \
    echo "${NTPSEC_SHA256} *ntpsec.tar.gz" | sha256sum -c - && \
    tar xzf ntpsec.tar.gz

COPY python-to-python3.patch /tmp/ntpsec-${NTPSEC_VERSION}/

RUN set -x && \
    cd /tmp/ntpsec-${NTPSEC_VERSION} && \
    patch -p1 -i python-to-python3.patch && \
    ./waf configure --prefix=/usr --python=python3 --enable-leap-smear --enable-mssntp --refclock=all && \
    ./waf build --verbose && \
    ./waf check --verbose && \
    ./waf install

#------------------------------------------------------------------------------#
FROM alpine:latest

ENV NTPSEC_RUN_DEPS python3 libressl libcap libseccomp py3-gpsd

RUN apk add --no-cache $NTPSEC_RUN_DEPS

COPY --from=0 /usr/sbin/ntpd /usr/sbin/ntpd
COPY --from=0 /usr/bin/ntp* /usr/bin/
COPY --from=0 /usr/lib/python3.8/site-packages/ntp/ /usr/lib/python3.8/site-packages/ntp/

RUN set -x && \
    mkdir -p /var/ntpsec/

COPY ntp.conf /etc/ntp.conf

EXPOSE 123/udp
EXPOSE 123/tcp

RUN ntpd --version

ENTRYPOINT ["/usr/sbin/ntpd"]

CMD ["-n", "-c", "/etc/ntp.conf"]
